%YAML:1.0
aruco_bc_nmarkers: 9
aruco_bc_mInfoType: 0
aruco_bc_markers:
   - { id:500, corners:[ [ -170., -170., 0. ], [ -70., -170., 0. ], [
       -70., -70., 0. ], [ -170., -70., 0. ] ] }
   - { id:218, corners:[ [ -50., -170., 0. ], [ 50., -170., 0. ], [ 50.,
       -70., 0. ], [ -50., -70., 0. ] ] }
   - { id:599, corners:[ [ 70., -170., 0. ], [ 170., -170., 0. ], [ 170.,
       -70., 0. ], [ 70., -70., 0. ] ] }
   - { id:300, corners:[ [ -170., -50., 0. ], [ -70., -50., 0. ], [ -70.,
       50., 0. ], [ -170., 50., 0. ] ] }
   - { id:964, corners:[ [ -50., -50., 0. ], [ 50., -50., 0. ], [ 50.,
       50., 0. ], [ -50., 50., 0. ] ] }
   - { id:293, corners:[ [ 70., -50., 0. ], [ 170., -50., 0. ], [ 170.,
       50., 0. ], [ 70., 50., 0. ] ] }
   - { id:203, corners:[ [ -170., 70., 0. ], [ -70., 70., 0. ], [ -70.,
       170., 0. ], [ -170., 170., 0. ] ] }
   - { id:221, corners:[ [ -50., 70., 0. ], [ 50., 70., 0. ], [ 50.,
       170., 0. ], [ -50., 170., 0. ] ] }
   - { id:561, corners:[ [ 70., 70., 0. ], [ 170., 70., 0. ], [ 170.,
       170., 0. ], [ 70., 170., 0. ] ] }
